name: Use template

on:
  push:

jobs:
  create:
    if: ${{ !github.event.repository.is_template }}
    permissions: 'write-all'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v4'

      - name: 'Update package.json'
        env:
          GITHUB_REPOSITORY_DESCRIPTION: ${{ github.event.repository.description }}
        run: ./.github/scripts/rename.sh "$GITHUB_REPOSITORY" "$GITHUB_REPOSITORY_DESCRIPTION"

      - name: 'Add rename summary'
        run: |
          echo "## Commit result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Remove files not needed in the user's copy of the template"
        run: |
          rm -f "./.github/scripts/rename.sh"
          rm -f "./.github/workflows/use-template.yml"
          rm -f "./pnpm-lock.yaml"

      - name: 'Add remove summary'
        run: |
          echo "## Remove result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: 'Update commit'
        uses: 'stefanzweifel/git-auto-commit-action@v4'
        with:
          commit_message: '🎉 Initial commit'
          commit_options: '--amend'
          push_options: '--force'
          skip_fetch: true

      - name: 'Add commit summary'
        run: |
          echo "## Commit result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
